services:
  db:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME:-pg}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-order_service}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/awtb/orderservice:latest
    container_name: ${API_CONTAINER_NAME:-order_service}
    ports:
      - ${SERVING_PORT}:${SERVING_PORT}
    env_file:
      - .env
    command: [ "uv", "run", "scripts/prod.sh" ]
    depends_on:
      - db

volumes:
  pgdata: