name: order-service-dev
services:
  app:
    container_name: order_service_devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - .git:/workspace/.git
    env_file:
      - ../.env
    environment:
      DB_PASSWORD: password
      DB_HOST: db
      SERVING_PORT: ${SERVING_PORT:-8000}
      DB_NAME: increment_db
    depends_on:
      - db
    ports:
      - "${SERVING_PORT:-8000}:${SERVING_PORT:-8000}"
      - "8089:8089" # For exposing locust stuff

    command: ["uv", "run", "scripts/dev.sh"]
  db:
    container_name: increment_db_devcontainer
    image: postgres:17
    environment:
      - POSTGRES_DB=increment_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  dev-container-extensions:
  dev-container-extensions-insiders: