name: order-service-dev
services:
  app:
    container_name: order_service_proj_devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - .git:/workspace/.git
    environment:
      DB_PASSWORD: order_service
      DB_HOST: db
      SERVING_PORT: ${SERVING_PORT:-8000}
      DB_NAME: order_service
      DB_USER: order_service_user
    depends_on:
      - db
    ports:
      - "${SERVING_PORT:-8000}:${SERVING_PORT:-8000}"
      - "8089:8089"

    command: ["uv", "run", "scripts/dev.sh"]
  db:
    container_name: order_service_proj_db
    image: postgres:17
    environment:
      - POSTGRES_DB=order_service
      - POSTGRES_USER=order_service_user
      - POSTGRES_PASSWORD=order_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  dev-container-extensions:
  dev-container-extensions-insiders: