name: order-service-dev
services:
  app:
    container_name: order_service_proj_devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - .git:/workspace/.git
    environment:
      DB_PASSWORD: order_service
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: order_service
      DB_USER: order_service_user
      SERVING_PORT: ${SERVING_PORT:-8000}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - db
      - redis
    ports:
      - "${SERVING_PORT:-8000}:${SERVING_PORT:-8000}"
      - "8089:8089"
    command: ["uv", "run", "scripts/dev.sh"]

  db:
    container_name: order_service_proj_db
    image: postgres:17
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: order_service_user
      POSTGRES_PASSWORD: order_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0-alpine
    container_name: order_service_proj_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: ${REDIS_USER:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD-redis}


    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka:
    container_name: ${KAFKA_CONTAINER_NAME:-kafka}
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      zookeeper:
        condition: service_healthy
    restart: always
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'echo > /dev/tcp/127.0.0.1/2181'"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  postgres_data:
  dev-container-extensions:
  dev-container-extensions-insiders: